<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>Ajout Client</title>

<meta name="description" content="Static &amp; Dynamic Tables" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

<!-- bootstrap & fontawesome -->
		<?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/bootstrap.css'); ?>
		<?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/font-awesome.css'); ?>

		<!-- page specific plugin styles -->

<!-- text fonts -->
		<?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/ace-fonts.css'); ?>

		<!-- ace styles -->
		<?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/ace.css'); ?>

		<!--[if lte IE 9]>
			<?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/ace-part2.css'); ?>
		<![endif]-->

<!--[if lte IE 9]>
		  <?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/ace-ie.css'); ?>
		<![endif]-->
<?php echo $this->headLink();?>
<!-- inline styles related to this page -->

<!-- ace settings handler -->
<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace-extra.js','text/javascript');?>
	

		
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/html5shiv.js','text/javascript');?>
	
		
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/respond.js','text/javascript');?>
		
	</head>

	<body 
	class="no-skin">
		<!-- #section:basics/navbar.layout -->
		<div id="navbar" class="navbar navbar-default">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

<div class="navbar-container" id="navbar-container">
	<!-- #section:basics/sidebar.mobile.toggle -->
	<button type="button" class="navbar-toggle menu-toggler pull-left"
		id="menu-toggler" data-target="#sidebar">
		<span class="sr-only">Toggle sidebar</span> <span class="icon-bar"></span>

		<span class="icon-bar"></span> <span class="icon-bar"></span>
	</button>

	<!-- /section:basics/sidebar.mobile.toggle -->
	<div class="navbar-header pull-left">
		<!-- #section:basics/navbar.layout.brand -->
		<a href="#" class="navbar-brand"> <small> <i class="fa fa-leaf"></i>
				Ace Admin
		</small>
		</a>

		<!-- /section:basics/navbar.layout.brand -->

		<!-- #section:basics/navbar.toggle -->

		<!-- /section:basics/navbar.toggle -->
	</div>

	<!-- #section:basics/navbar.dropdown -->
	<div class="navbar-buttons navbar-header pull-right" role="navigation">
		<ul class="nav ace-nav">
			<li class="grey"><a data-toggle="dropdown" class="dropdown-toggle"
				href="#"> <i class="ace-icon fa fa-tasks"></i> <span
					class="badge badge-grey">4</span>
			</a>

				<ul
					class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
					<li class="dropdown-header"><i class="ace-icon fa fa-check"></i> 4
						Tasks to complete</li>

					<li class="dropdown-content">
						<ul class="dropdown-menu dropdown-navbar">
							<li><a href="#">
									<div class="clearfix">
										<span class="pull-left">Software Update</span> <span
											class="pull-right">65%</span>
									</div>

									<div class="progress progress-mini">
										<div style="width: 65%" class="progress-bar"></div>
									</div>
							</a></li>

							<li><a href="#">
									<div class="clearfix">
										<span class="pull-left">Hardware Upgrade</span> <span
											class="pull-right">35%</span>
									</div>

									<div class="progress progress-mini">
										<div style="width: 35%"
											class="progress-bar progress-bar-danger"></div>
									</div>
							</a></li>

							<li><a href="#">
									<div class="clearfix">
										<span class="pull-left">Unit Testing</span> <span
											class="pull-right">15%</span>
									</div>

									<div class="progress progress-mini">
										<div style="width: 15%"
											class="progress-bar progress-bar-warning"></div>
									</div>
							</a></li>

							<li><a href="#">
									<div class="clearfix">
										<span class="pull-left">Bug Fixes</span> <span
											class="pull-right">90%</span>
									</div>

									<div class="progress progress-mini progress-striped active">
										<div style="width: 90%"
											class="progress-bar progress-bar-success"></div>
									</div>
							</a></li>
						</ul>
					</li>

					<li class="dropdown-footer"><a href="#"> See tasks with details <i
							class="ace-icon fa fa-arrow-right"></i>
					</a></li>
				</ul></li>

			<li class="purple"><a data-toggle="dropdown" class="dropdown-toggle"
				href="#"> <i class="ace-icon fa fa-bell icon-animated-bell"></i> <span
					class="badge badge-important">8</span>
			</a>

				<ul
					class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
					<li class="dropdown-header"><i
						class="ace-icon fa fa-exclamation-triangle"></i> 8 Notifications</li>

					<li class="dropdown-content">
						<ul class="dropdown-menu dropdown-navbar navbar-pink">
							<li><a href="#">
									<div class="clearfix">
										<span class="pull-left"> <i
											class="btn btn-xs no-hover btn-pink fa fa-comment"></i> New
											Comments
										</span> <span class="pull-right badge badge-info">+12</span>
									</div>
							</a></li>

							<li><a href="#"> <i class="btn btn-xs btn-primary fa fa-user"></i>
									Bob just signed up as an editor ...
							</a></li>

							<li><a href="#">
									<div class="clearfix">
										<span class="pull-left"> <i
											class="btn btn-xs no-hover btn-success fa fa-shopping-cart"></i>
											New Orders
										</span> <span class="pull-right badge badge-success">+8</span>
									</div>
							</a></li>

							<li><a href="#">
									<div class="clearfix">
										<span class="pull-left"> <i
											class="btn btn-xs no-hover btn-info fa fa-twitter"></i>
											Followers
										</span> <span class="pull-right badge badge-info">+11</span>
									</div>
							</a></li>
						</ul>
					</li>

					<li class="dropdown-footer"><a href="#"> See all notifications <i
							class="ace-icon fa fa-arrow-right"></i>
					</a></li>
				</ul></li>

			<li class="green"><a data-toggle="dropdown" class="dropdown-toggle"
				href="#"> <i class="ace-icon fa fa-envelope icon-animated-vertical"></i>
					<span class="badge badge-success">5</span>
			</a>

				<ul
					class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
					<li class="dropdown-header"><i class="ace-icon fa fa-envelope-o"></i>
						5 Messages</li>

					<li class="dropdown-content">
						<ul class="dropdown-menu dropdown-navbar">
							<li><a href="#" class="clearfix"> 
						
							<img src="<?php  echo  $this->baseUrl()?> /avatars/avatar.png" alt="Alex's Avatar" /> 
									<span class="msg-body"> <span
										class="msg-title"> <span class="blue">Alex:</span> Ciao sociis
											natoque penatibus et auctor ...
									</span> <span class="msg-time"> <i
											class="ace-icon fa fa-clock-o"></i> <span>a moment ago</span>
									</span>
								</span>
							</a></li>

							<li><a href="#" class="clearfix">
							 <img src="<?php  echo  $this->baseUrl()?>/avatars/avatar3.png"
							 
									
									alt="Susan's Avatar" /> <span class="msg-body"> <span
										class="msg-title"> <span class="blue">Susan:</span> Vestibulum
											id ligula porta felis euismod ...
									</span> <span class="msg-time"> <i
											class="ace-icon fa fa-clock-o"></i> <span>20 minutes ago</span>
									</span>
								</span>
							</a></li>

							<li><a href="#" class="clearfix"> 
									<img src="<?php  echo  $this->baseUrl()?>/avatars/avatar4.png"
									alt="Bob's Avatar" /> <span class="msg-body"> <span
										class="msg-title"> <span class="blue">Bob:</span> Nullam quis
											risus eget urna mollis ornare ...
									</span> <span class="msg-time"> <i
											class="ace-icon fa fa-clock-o"></i> <span>3:15 pm</span>
									</span>
								</span>
							</a></li>

							<li><a href="#" class="clearfix"> 
							<img src="<?php  echo  $this->baseUrl()?>/avatars/avatar2.png" class="msg-photo"
									alt="Kate's Avatar" />
									 <span class="msg-body"> <span
										class="msg-title"> <span class="blue">Kate:</span> Ciao sociis
											natoque eget urna mollis ornare ...
										src="<?php  echo  $this->baseUrl()?>../public/avatars/avatar2.png" class="msg-photo"
											
									</span> <span class="msg-time"> <i
											class="ace-icon fa fa-clock-o"></i> <span>1:33 pm</span>
									</span>
								</span>
							</a></li>

							<li><a href="#" class="clearfix"> 
									<img src="<?php  echo  $this->baseUrl()?>/avatars/avatar5.png"
									alt="Fred's Avatar" /> <span class="msg-body"> <span
										class="msg-title"> <span class="blue">Fred:</span> Vestibulum
											id penatibus et auctor ...
									</span> <span class="msg-time"> <i
											class="ace-icon fa fa-clock-o"></i> <span>10:09 am</span>
									</span>
								</span>
							</a></li>
						</ul>
					</li>

					<li class="dropdown-footer"><a href="inbox.html"> See all messages
							<i class="ace-icon fa fa-arrow-right"></i>
					</a></li>
				</ul></li>

			<!-- #section:basics/navbar.user_menu -->
			<li class="light-blue"><a data-toggle="dropdown" href="#"
				class="dropdown-toggle">
				 <img class="nav-user-photo"
					src="<?php echo  $this->baseUrl()?>/avatars/user.jpg" alt="Jason's Photo" /> 
					<span
					class="user-info"> <small>Welcome,</small> Jason
				</span> <i class="ace-icon fa fa-caret-down"></i>
			</a>

				<ul
					class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
					<li><a href="#"> <i class="ace-icon fa fa-cog"></i> Settings
					</a></li>

					<li><a href="profile.html"> <i class="ace-icon fa fa-user"></i>
							Profile
					</a></li>

					<li class="divider"></li>

					<li><a href="#"> <i class="ace-icon fa fa-power-off"></i> Logout
					</a></li>
				</ul></li>

			<!-- /section:basics/navbar.user_menu -->
		</ul>
	</div>

	<!-- /section:basics/navbar.dropdown -->
</div>
<!-- /.navbar-container -->
</div>

<!-- /section:basics/navbar.layout -->
<div class="main-container" id="main-container">
	<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

	<!-- #section:basics/sidebar -->
	<div id="sidebar" class="sidebar                  responsive"
		data-sidebar="true" data-sidebar-scroll="true"
		data-sidebar-hover="true">
		<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
				</script>

		<div class="sidebar-shortcuts" id="sidebar-shortcuts">
			<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
				<button class="btn btn-success">
					<i class="ace-icon fa fa-signal"></i>
				</button>

				<button class="btn btn-info">
					<i class="ace-icon fa fa-pencil"></i>
				</button>

				<!-- #section:basics/sidebar.layout.shortcuts -->
				<button class="btn btn-warning">
					<i class="ace-icon fa fa-users"></i>
				</button>

				<button class="btn btn-danger">
					<i class="ace-icon fa fa-cogs"></i>
				</button>

				<!-- /section:basics/sidebar.layout.shortcuts -->
			</div>

			<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
				<span class="btn btn-success"></span> <span class="btn btn-info"></span>

				<span class="btn btn-warning"></span> <span class="btn btn-danger"></span>
			</div>
		</div>
		<!-- /.sidebar-shortcuts -->

		<ul class="nav nav-list">
			<li class="active"><a href="index.html"> <i
					class="menu-icon bleu ace-icon fa fa-home bigger-120"></i> <span
					class="menu-text">Accueil</span>
			</a> <b class="arrow"></b></li>







			<li class=""><a href="#" class="dropdown-toggle"> <i
					class="menu-icon fa fa-users"></i> <span class="menu-text"> Clients
				</span> <b class="arrow fa fa-angle-down"></b>
			</a> <b class="arrow"></b>

				<ul class="submenu">
					<li class=""><a href="Ajout_client.html"> <i
							class="menu-icon fa fa-caret-right"></i> Ajouter un client
					</a> <b class="arrow"></b></li>

					<li class=""><a href="jqgrid.html"> <i
							class="menu-icon fa fa-caret-right"></i> Lister les clients
					</a> <b class="arrow"></b></li>
				</ul></li>
			<li class=""><a href="#" class="dropdown-toggle"> <i
					class="menu-icon fa fa-shopping-cart"></i> <span class="menu-text">
						Fournisseurs </span> <b class="arrow fa fa-angle-down"></b>
			</a> <b class="arrow"></b>

				<ul class="submenu">
					<li class=""><a href="Ajout_frs.html"> <i
							class="menu-icon fa fa-caret-right"></i> Ajouter un fourrnisseur
					</a> <b class="arrow"></b></li>

					<li class=""><a href="jqgrid.html"> <i
							class="menu-icon fa fa-caret-right"></i> Lister les fourrnisseurs
					</a> <b class="arrow"></b></li>
				</ul></li>
			<li class=""><a href="#" class="dropdown-toggle"> <i
					class="menu-icon fa fa-table"></i> <span class="menu-text"> Bande
						commande </span> <b class="arrow fa fa-angle-down"></b>
			</a> <b class="arrow"></b>

				<ul class="submenu">
					<li class=""><a href="creer_bd.html"> <i
							class="menu-icon fa fa-caret-right"></i> Créer une bande de
							commande
					</a> <b class="arrow"></b></li>

					<li class=""><a href="jqgrid.html"> <i
							class="menu-icon fa fa-caret-right"></i> Lister les bandes de
							commandes
					</a> <b class="arrow"></b></li>
				</ul></li>
			<li class=""><a href="#" class="dropdown-toggle"> <i
					class="menu-icon fa fa-file-text-o"></i> <span class="menu-text">
						Facturation </span> <b class="arrow fa fa-angle-down"></b>
			</a> <b class="arrow"></b>

				<ul class="submenu">
					<li class=""><a href="tables.html"> <i
							class="menu-icon fa fa-caret-right"></i> Créer une facture
					</a> <b class="arrow"></b></li>

					<li class=""><a href="jqgrid.html"> <i
							class="menu-icon fa fa-caret-right"></i> Lister les factures
					</a> <b class="arrow"></b></li>
				</ul></li>

			<b class="arrow"></b>




			<b class="arrow"></b>



		</ul>
		<!-- /.nav-list -->

		<!-- #section:basics/sidebar.layout.minimize -->
		<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
			<i class="ace-icon fa fa-angle-double-left"
				data-icon1="ace-icon fa fa-angle-double-left"
				data-icon2="ace-icon fa fa-angle-double-right"></i>
		</div>

		<!-- /section:basics/sidebar.layout.minimize -->
		<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
	</div>
	<!-- /section:basics/sidebar -->
	<div class="main-content">
		<div class="main-content-inner">
			<!-- #section:basics/content.breadcrumbs -->
			<div class="breadcrumbs" id="breadcrumbs">
				<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

				<ul class="breadcrumb">
					<li><i class="ace-icon fa fa-home home-icon"></i> <a href="#">Accueil</a>
					</li>

					<li><a href="#">Clients</a></li>
					<li class="active">Ajout</li>
				</ul>
				<!-- /.breadcrumb -->

				<!-- #section:basics/content.searchbox -->
				<div class="nav-search" id="nav-search">
					<form class="form-search">
						<span class="input-icon"> <input type="text"
							placeholder="Search ..." class="nav-search-input"
							id="nav-search-input" autocomplete="off" /> <i
							class="ace-icon fa fa-search nav-search-icon"></i>
						</span>
					</form>
				</div>
				<!-- /.nav-search -->

				<!-- /section:basics/content.searchbox -->
			</div>

			<!-- /section:basics/content.breadcrumbs -->
			<div class="page-content">
				<!-- #section:settings.box -->
				<div class="ace-settings-container" id="ace-settings-container">
					<div class="btn btn-app btn-xs btn-warning ace-settings-btn"
						id="ace-settings-btn">
						<i class="ace-icon fa fa-cog bigger-130"></i>
					</div>

					<div class="ace-settings-box clearfix" id="ace-settings-box">
						<div class="pull-left width-50">
							<!-- #section:settings.skins -->
							<div class="ace-settings-item">
								<div class="pull-left">
									<select id="skin-colorpicker" class="hide">
										<option data-skin="no-skin" value="#438EB9">#438EB9</option>
										<option data-skin="skin-1" value="#222A2D">#222A2D</option>
										<option data-skin="skin-2" value="#C6487E">#C6487E</option>
										<option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
									</select>
								</div>
								<span>&nbsp; Choose Skin</span>
							</div>

							<!-- /section:settings.skins -->

							<!-- #section:settings.navbar -->
							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-navbar" /> <label class="lbl"
									for="ace-settings-navbar"> Fixed Navbar</label>
							</div>

							<!-- /section:settings.navbar -->

							<!-- #section:settings.sidebar -->
							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-sidebar" /> <label class="lbl"
									for="ace-settings-sidebar"> Fixed Sidebar</label>
							</div>

							<!-- /section:settings.sidebar -->

							<!-- #section:settings.breadcrumbs -->
							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-breadcrumbs" /> <label class="lbl"
									for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
							</div>

							<!-- /section:settings.breadcrumbs -->

							<!-- #section:settings.rtl -->
							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-rtl" /> <label class="lbl"
									for="ace-settings-rtl"> Right To Left (rtl)</label>
							</div>

							<!-- /section:settings.rtl -->

							<!-- #section:settings.container -->
							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-add-container" /> <label class="lbl"
									for="ace-settings-add-container"> Inside <b>.container</b>
								</label>
							</div>

							<!-- /section:settings.container -->
						</div>
						<!-- /.pull-left -->

						<div class="pull-left width-50">
							<!-- #section:basics/sidebar.options -->
							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-hover" /> <label class="lbl"
									for="ace-settings-hover"> Submenu on Hover</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-compact" /> <label class="lbl"
									for="ace-settings-compact"> Compact Sidebar</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2"
									id="ace-settings-highlight" /> <label class="lbl"
									for="ace-settings-highlight"> Alt. Active Item</label>
							</div>

							<!-- /section:basics/sidebar.options -->
						</div>
						<!-- /.pull-left -->
					</div>
					<!-- /.ace-settings-box -->
				</div>
				<!-- /.ace-settings-container -->

				<!-- /section:settings.box -->
				<div class="page-header">
					<h1>
						Clients <small> <i class="ace-icon fa fa-angle-double-right"></i>
							Ajouter un Client
						</small>
					</h1>
				</div>
				<!-- /.page-header -->

				<div class="row">
					<div class="col-xs-12">
						<table width="1100" height="442" border="0">
							<tr>
								<td>&nbsp;&nbsp;&nbsp;<label> Identifiant </label></td>
								<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input
									readonly="" type="text" class="col-xs-10 col-sm-5"
									id="form-input-readonly" value="Auto-Saisie"></td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>&nbsp;&nbsp;&nbsp;<label> Nom Société </label></td>
								<td>&nbsp;&nbsp;&nbsp;&nbsp;<input class="input-xlarge"
									type="text" id="form-field-4" placeholder="Nom Société"></td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td height="88">&nbsp;&nbsp;&nbsp;<label> Adresse Postale </label></td>
								<td>&nbsp;&nbsp;&nbsp;&nbsp;<input class="input-xlarge"
									type="text" id="form-field-4" placeholder="Adresse Postale"></td>
								<td>&nbsp;&nbsp;&nbsp;<label> Contact Personne </label></td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>&nbsp;&nbsp;&nbsp;<label> Numéro Téléphone </label></td>
								<td class="input-group"><span> <i class="ace-icon fa fa-phone"></i>
										<input class="input-xlarge" type="text" id="form-field-4"
										placeholder="Numéro de Téléphone"></span></td>
								<td>&nbsp;&nbsp;&nbsp;<label> Nom contact personne </label></td>
								<td>&nbsp;&nbsp;&nbsp;&nbsp;<input class="input-xlarge"
									type="text" id="form-field-4"
									placeholder="Nom contact personne"></td>
							</tr>
							<tr>
								<td>&nbsp;&nbsp;&nbsp;<label> Numéro Fax </label></td>
								<td class="input-group"><span> <i class="ace-icon fa fa-fax"></i>
										<input class="input-xlarge" type="text" id="form-field-4"
										placeholder="Numéro de Fax"></span></td>
								<td>&nbsp;&nbsp;&nbsp;<label> Numéro Téléphone </label></td>
								<td class="input-group"><span> <i class="ace-icon fa fa-phone"></i>
										<input class="input-xlarge" type="text" id="form-field-4"
										placeholder="Numéro de Téléphone"></span></td>
							</tr>
							<tr>
								<td>&nbsp;&nbsp;&nbsp;<label> Site Web </label></td>
								<td class="input-group"><span> <i class="ace-icon fa fa-desktop"></i>
										<input class="input-xlarge" type="text" id="form-field-4"
										placeholder="Site Web"></span></td>
								<td>&nbsp;&nbsp;&nbsp;<label> Numéro Téléphone Mobile </label></td>
								<td class="input-group"><span> <i
										class="ace-icon fa fa-minus-square"></i> <input
										class="input-xlarge" type="text" id="form-field-4"
										placeholder="Numéro de Téléphone Mobile"></span></td>
							</tr>
							<tr>
								<td>&nbsp;&nbsp;&nbsp;<label> E-mail</label></td>
								<td class="input-group"><span> <i
										class="ace-icon fa fa-envelope"></i> <input
										class="input-xlarge" type="text" id="form-field-4"
										placeholder="E-mail"></span></td>
								<td>&nbsp;&nbsp;&nbsp;<label> E-mail</label></td>
								<td class="input-group"><span> <i
										class="ace-icon fa fa-envelope"></i> <input
										class="input-xlarge" type="text" id="form-field-4"
										placeholder="E-mail"></span></td>
							</tr>
							<tr>
								<td>&nbsp;&nbsp;&nbsp;<label> Description</label></td>
							</tr>
						</table width="1100" height="442" border="0">
						<table>
							<tr>
								<td><textarea class="form-control" id="form-field-8"
										placeholder="Description de client"></textarea></td>
							</tr>

						</table>
						<div class="clearfix form-actions">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn btn-info" type="button">
									<i class="ace-icon fa fa-check bigger-110"></i> Submit
								</button>

								&nbsp; &nbsp; &nbsp;
								<button class="btn" type="reset">
									<i class="ace-icon fa fa-undo bigger-110"></i> Reset
								</button>
							</div>
						</div>
					</div>
					<!-- /.col -->
				</div>
				<!-- /.row -->
			</div>
			<!-- /.page-content -->
		</div>
	</div>
	<!-- /.main-content -->

	<div class="footer">
		<div class="footer-inner">
			<!-- #section:basics/footer -->
			<div class="footer-content">
				<span class="bigger-120"> <span class="blue bolder">Ace</span>
					Application &copy; 2013-2014
				</span> &nbsp; &nbsp; <span class="action-buttons"> <a href="#"> <i
						class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
				</a> <a href="#"> <i
						class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
				</a> <a href="#"> <i
						class="ace-icon fa fa-rss-square orange bigger-150"></i>
				</a>
				</span>
			</div>

			<!-- /section:basics/footer -->
		</div>
	</div>

	<a href="#" id="btn-scroll-up"
		class="btn-scroll-up btn btn-sm btn-inverse"> <i
		class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
	</a>
</div>
<!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->
<script type="text/javascript">
			window.jQuery || document.write("<script src='<?php  echo  $this->baseUrl()?>/js/jquery.js'>"+"<"+"/script>");
		</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='<?php  echo  $this->baseUrl()?>/js/jquery1x.js'>"+"<"+"/script>");
</script>
<![endif]-->
<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?php  echo  $this->baseUrl()?>/js/jquery.mobile.custom.js'>"+"<"+"/script>");
		</script>
		
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/bootstrap.js','text/javascript');?>
		

		<!-- page specific plugin scripts -->
		
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/dataTables/jquery.dataTables.js','text/javascript');?>
		
				<?php $this->headScript()->appendFile($this->baseUrl().'/js/dataTables/jquery.dataTables.bootstrap.js','text/javascript');?>
		
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/dataTables/extensions/TableTools/js/dataTables.tableTools.js','text/javascript');?>
		
			<?php $this->headScript()->appendFile($this->baseUrl().'/js/dataTables/extensions/ColVis/js/dataTables.colVis.js','text/javascript');?>
		

		<!-- ace scripts -->
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.scroller.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.colorpicker.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.fileinput.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.typeahead.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.wysiwyg.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.spinner.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.treeview.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.wizard.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.aside.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.ajax-content.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.touch-drag.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.sidebar.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.sidebar-scroll-1.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.submenu-hover.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.widget-box.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.settings.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.settings-rtl.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.settings-skin.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.widget-on-reload.js','text/javascript');?>
		<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.searchbox-autocomplete.js','text/javascript');?>

		<!-- inline scripts related to this page -->
<script type="text/javascript">
			jQuery(function($) {
				//initiate dataTables plugin
				var oTable1 = 
				$('#dynamic-table')
				//.wrap("<div class='dataTables_borderWrap' />")   //if you are applying horizontal scrolling (sScrollX)
				.dataTable( {
					bAutoWidth: false,
					"aoColumns": [
					  { "bSortable": false },
					  null, null,null, null, null,
					  { "bSortable": false }
					],
					"aaSorting": [],
			
					//,
					//"sScrollY": "200px",
					//"bPaginate": false,
			
					//"sScrollX": "100%",
					//"sScrollXInner": "120%",
					//"bScrollCollapse": true,
					//Note: if you are applying horizontal scrolling (sScrollX) on a ".table-bordered"
					//you may want to wrap the table inside a "div.dataTables_borderWrap" element
			
					//"iDisplayLength": 50
			    } );
				//oTable1.fnAdjustColumnSizing();
			
			
				//TableTools settings
				TableTools.classes.container = "btn-group btn-overlap";
				TableTools.classes.print = {
					"body": "DTTT_Print",
					"info": "tableTools-alert gritter-item-wrapper gritter-info gritter-center white",
					"message": "tableTools-print-navbar"
				}
			
				//initiate TableTools extension
				var tableTools_obj = new $.fn.dataTable.TableTools( oTable1, {
					"sSwfPath": "../assets/js/dataTables/extensions/TableTools/swf/copy_csv_xls_pdf.swf", //in Ace demo ../assets will be replaced by correct assets path
					
					"sRowSelector": "td:not(:last-child)",
					"sRowSelect": "multi",
					"fnRowSelected": function(row) {
						//check checkbox when row is selected
						try { $(row).find('input[type=checkbox]').get(0).checked = true }
						catch(e) {}
					},
					"fnRowDeselected": function(row) {
						//uncheck checkbox
						try { $(row).find('input[type=checkbox]').get(0).checked = false }
						catch(e) {}
					},
			
					"sSelectedClass": "success",
			        "aButtons": [
						{
							"sExtends": "copy",
							"sToolTip": "Copy to clipboard",
							"sButtonClass": "btn btn-white btn-primary btn-bold",
							"sButtonText": "<i class='fa fa-copy bigger-110 pink'></i>",
							"fnComplete": function() {
								this.fnInfo( '<h3 class="no-margin-top smaller">Table copied</h3>\
									<p>Copied '+(oTable1.fnSettings().fnRecordsTotal())+' row(s) to the clipboard.</p>',
									1500
								);
							}
						},
						
						{
							"sExtends": "csv",
							"sToolTip": "Export to CSV",
							"sButtonClass": "btn btn-white btn-primary  btn-bold",
							"sButtonText": "<i class='fa fa-file-excel-o bigger-110 green'></i>"
						},
						
						{
							"sExtends": "pdf",
							"sToolTip": "Export to PDF",
							"sButtonClass": "btn btn-white btn-primary  btn-bold",
							"sButtonText": "<i class='fa fa-file-pdf-o bigger-110 red'></i>"
						},
						
						{
							"sExtends": "print",
							"sToolTip": "Print view",
							"sButtonClass": "btn btn-white btn-primary  btn-bold",
							"sButtonText": "<i class='fa fa-print bigger-110 grey'></i>",
							
							"sMessage": "<div class='navbar navbar-default'><div class='navbar-header pull-left'><a class='navbar-brand' href='#'><small>Optional Navbar &amp; Text</small></a></div></div>",
							
							"sInfo": "<h3 class='no-margin-top'>Print view</h3>\
									  <p>Please use your browser's print function to\
									  print this table.\
									  <br />Press <b>escape</b> when finished.</p>",
						}
			        ]
			    } );
				//we put a container before our table and append TableTools element to it
			    $(tableTools_obj.fnContainer()).appendTo($('.tableTools-container'));
				
				//also add tooltips to table tools buttons
				//addding tooltips directly to "A" buttons results in buttons disappearing (weired! don't know why!)
				//so we add tooltips to the "DIV" child after it becomes inserted
				//flash objects inside table tools buttons are inserted with some delay (100ms) (for some reason)
				setTimeout(function() {
					$(tableTools_obj.fnContainer()).find('a.DTTT_button').each(function() {
						var div = $(this).find('> div');
						if(div.length > 0) div.tooltip({container: 'body'});
						else $(this).tooltip({container: 'body'});
					});
				}, 200);
				
				
				
				//ColVis extension
				var colvis = new $.fn.dataTable.ColVis( oTable1, {
					"buttonText": "<i class='fa fa-search'></i>",
					"aiExclude": [0, 6],
					"bShowAll": true,
					//"bRestore": true,
					"sAlign": "right",
					"fnLabel": function(i, title, th) {
						return $(th).text();//remove icons, etc
					}
					
				}); 
				
				//style it
				$(colvis.button()).addClass('btn-group').find('button').addClass('btn btn-white btn-info btn-bold')
				
				//and append it to our table tools btn-group, also add tooltip
				$(colvis.button())
				.prependTo('.tableTools-container .btn-group')
				.attr('title', 'Show/hide columns').tooltip({container: 'body'});
				
				//and make the list, buttons and checkboxed Ace-like
				$(colvis.dom.collection)
				.addClass('dropdown-menu dropdown-light dropdown-caret dropdown-caret-right')
				.find('li').wrapInner('<a href="javascript:void(0)" />') //'A' tag is required for better styling
				.find('input[type=checkbox]').addClass('ace').next().addClass('lbl padding-8');
			
			
				
				/////////////////////////////////
				//table checkboxes
				$('th input[type=checkbox], td input[type=checkbox]').prop('checked', false);
				
				//select/deselect all rows according to table header checkbox
				$('#dynamic-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function(){
					var th_checked = this.checked;//checkbox inside "TH" table header
					
					$(this).closest('table').find('tbody > tr').each(function(){
						var row = this;
						if(th_checked) tableTools_obj.fnSelect(row);
						else tableTools_obj.fnDeselect(row);
					});
				});
				
				//select/deselect a row when the checkbox is checked/unchecked
				$('#dynamic-table').on('click', 'td input[type=checkbox]' , function(){
					var row = $(this).closest('tr').get(0);
					if(!this.checked) tableTools_obj.fnSelect(row);
					else tableTools_obj.fnDeselect($(this).closest('tr').get(0));
				});
				
			
				
				
					$(document).on('click', '#dynamic-table .dropdown-toggle', function(e) {
					e.stopImmediatePropagation();
					e.stopPropagation();
					e.preventDefault();
				});
				
				
				//And for the first simple table, which doesn't have TableTools or dataTables
				//select/deselect all rows according to table header checkbox
				var active_class = 'active';
				$('#simple-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function(){
					var th_checked = this.checked;//checkbox inside "TH" table header
					
					$(this).closest('table').find('tbody > tr').each(function(){
						var row = this;
						if(th_checked) $(row).addClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', true);
						else $(row).removeClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', false);
					});
				});
				
				//select/deselect a row when the checkbox is checked/unchecked
				$('#simple-table').on('click', 'td input[type=checkbox]' , function(){
					var $row = $(this).closest('tr');
					if(this.checked) $row.addClass(active_class);
					else $row.removeClass(active_class);
				});
			
				
			
				/********************************/
				//add tooltip for small view action buttons in dropdown menu
				$('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});
				
				//tooltip placement on right or left
				function tooltip_placement(context, source) {
					var $source = $(source);
					var $parent = $source.closest('table')
					var off1 = $parent.offset();
					var w1 = $parent.width();
			
					var off2 = $source.offset();
					//var w2 = $source.width();
			
					if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';
					return 'left';
				}
			
			})
		</script>

<!-- the following scripts are used in demo only for onpage help and you don't need them -->
		<?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/ace.onpage-help.css'); ?>
	   <?php $this->headLink() ->appendStylesheet($this->baseUrl().'/css/themes/sunburst.css'); ?>
		<script type="text/javascript"> ace.vars['base'] = '..';
</script>
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/elements.onpage-help.js','text/javascript');?>
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/ace/ace.onpage-help.js','text/javascript');?>
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/js/rainbow.js','text/javascript');?>
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/js/language/generic.js','text/javascript');?>
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/js/language/html.js','text/javascript');?>
    <?php $this->headScript()->appendFile($this->baseUrl().'/js/js/language/css.js','text/javascript');?>
	<?php $this->headScript()->appendFile($this->baseUrl().'/js/js/language/javascript.js','text/javascript');?>
	<?php echo $this->headScript();?>
	</body>
</html>
